const defaultXY = {
  x: -73.9565759733611,
  y: 40.7992461674802,
};
export const data = [
  {
    ...defaultXY,
    id: 'a',
    unique_squirrel_id: 'a',
    date: '10182018',
    primary_fur_color: 'Gray',
    location: 'Ground',
    running: true,
    climbing: true,
    eating: true,
    foraging: false,
    approaches: true,
    kuks: false,
    quaas: true,
  },
  {
    ...defaultXY,
    id: 'b',
    unique_squirrel_id: 'b',
    date: '10172018',
    primary_fur_color: 'Black',
    highlight_fur_color: 'Cinnamon',
    location: 'Tree',
    running: false,
    chasing: true,
    eating: false,
    kuks: true,
    quaas: false,
    other_activities: 'foraging',
  },
  {
    ...defaultXY,
    id: 'c',
    unique_squirrel_id: 'c',
    date: '10202018',
    primary_fur_color: 'Gray',
    highlight_fur_color: 'Black',
    running: true,
    chasing: false,
    climbing: false,
    eating: false,
    foraging: true,
    approaches: false,
    kuks: true,
    other_interactions: 'ran away',
  },
  {
    ...defaultXY,
    id: 'd',
    unique_squirrel_id: 'd',
    date: '10062018',
    primary_fur_color: 'Cinnamon',
    highlight_fur_color: 'Grey',
    location: 'Ground',
    running: false,
    chasing: false,
    climbing: true,
    eating: true,
    foraging: false,
    other_activities: '',
    other_interactions: null,
  },
  {
    ...defaultXY,
    id: 'e',
    unique_squirrel_id: 'e',
    date: '10092018',
    highlight_fur_color: 'Cinnamon',
    location: 'Tree',
    chasing: true,
    climbing: true,
    foraging: true,
    approaches: true,
    kuks: false,
    quaas: true,
  },
];
